# This is a basic workflow to help you get started with Actions

name: Add new redirect rule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to forward to'
        required: true
      shortcode:
        description: 'Custom shortcode for this URL'
        default: ''
        required: false
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NPM modules
        run: npm i

      # Runs a set of commands using the runners shell
      - name: Add a new shortcode to redirects file
        run: npm run shortern ${{ github.event.inputs.url }} ${{ github.event.inputs.shortcode }}
